---
- name: check for existing install...
  become: yes
  stat:
    path: '{{hub_install_dir}}'
  changed_when: False
  register: hub_binary
- when: not hub_binary.stat.exists
  block:
    - name: download archive
      become: yes
      become_user: root
      get_url:
        url: '{{hub_tgz_url}}'
        dest: /tmp/{{hub_tgz}}
        mode: 0644

    - name: unarchive to install parent dir
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{hub_tgz}}
        dest: '{{hub_install_parent_dir}}'
        creates: '{hub_install_dir}}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{hub_tgz}}
        state: absent

- name: ensure target directories exist
  become: yes
  become_user: root
  with_items:
    - '{{hub_install_parent_dir}}/bin'
    - '{{hub_install_parent_dir}}/share/man/man1'
  file:
    path: '{{item}}'
    state: directory
    mode: 0755

- name: link up
  become: yes
  become_user: root
  with_items:
    - bin/hub
    - share/man/man1/hub.1
  file:
    src: '{{hub_install_dir}}/{{item}}'
    dest: '{{hub_install_parent_dir}}/{{item}}'
    state: link

- name: link hub completions
  become: yes
  become_user: root
  with_items:
    - hub.bash_completion.sh
  file:
    src: '{{hub_install_dir}}/etc/{{item}}'
    dest: '{{hub_bash_completion_d}}/{{item}}'
    state: link
